version: '3'
networks:
  service_net:
    external:
      name: service_net
services:
  frontend:
    container_name: sysstats_frontend
    build: ./frontend
    networks:
    - service_net
    ports:
    - "3031:3031" # uWSGI
    - "32770:32770" # http
    depends_on:
    - backend
    - redis
    restart: unless-stopped
  backend:
    container_name: sysstats_backend
    build: ./backend
    networks:
    - service_net
    depends_on:
    - redis
    restart: unless-stopped
  redis:
    container_name: sysstats_redis
    image: redis:latest
    networks:
    - service_net
    restart: unless-stopped
  daemon:
    container_name: sysstats_daemon
    build: ./daemon
    networks:
    - service_net
    depends_on:
    - redis
    restart: unless-stopped
