version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
  daemon:
    build: ./daemon
